zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: ${oc.env:ZOTERO_INCLUDE}

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: ${oc.env:SMTP_SERVER}
  smtp_port: ${oc.env:SMTP_PORT}
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    max_tokens: 32768
    model: ${oc.env:MODEL_NAME}

source:
  arxiv:
    category: ["cs.AI","cs.CV","cs.LG"]

executor:
  debug: ${oc.env:DEBUG,false}
  source: ['arxiv']
  max_paper_num: 40
